### ISSUE TITLE
not trying to be a jerk.

### ISSUE THREAD

**Issue by bdmorin** [Bechma/Bashmap#1]
```
hyperfine -r 3 'bash bashmap.sh 10.0.0.1' 'nmap -sT -p- --open -PN 10.0.0.1'                            

Benchmark 1: bash bashmap.sh 10.0.0.1
  Time (abs ≡):        153.102 s               [User: 236.677 s, System: 943.119 s]

Benchmark 2: nmap -sT -p- --open -PN 10.0.0.1
  Time (abs ≡):        76.857 s               [User: 0.671 s, System: 7.219 s]

Summary
  'nmap -sT -p- --open -PN 10.0.0.1' ran
    1.99 times faster than 'bash bashmap.sh 10.0.0.1'
```

Was just curious.

**Comment by Bechma** [comment]
This repository was created just as a meme to feed a twitter thread.

It's replicating nmap but in a very inneficient and unperformant way(it can even hangs indefinetly if your target has a firewall), this is why it takes 2x in your benchmark.

However, if you think that it can improve more with basic linux tools, I'm open to PR

**Comment by daniel-cues** [comment]
That's because bashmap uses quantum computing, so the time is actually sqrt(153.102) = 12.3734s

**Comment by bdmorin** [comment]
>This repository was created just as a meme to feed a twitter thread.

Still have the thread?
